// Auto-generated by scripts/layout-network.ts
// Run: npx tsx scripts/layout-network.ts

export const nodePositions: Record<string, { x: number; y: number }> = {
  "sleep_disruption": {
    "x": 50,
    "y": 50
  },
  "exercise": {
    "x": 50,
    "y": 120
  },
  "aging": {
    "x": 50,
    "y": 320
  },
  "fsh_elevated": {
    "x": 50,
    "y": 520
  },
  "familial_ad_mutations": {
    "x": 50,
    "y": 590
  },
  "apoe_genotype": {
    "x": 50,
    "y": 660
  },
  "homocysteine": {
    "x": 50,
    "y": 860
  },
  "as01_adjuvant": {
    "x": 50,
    "y": 930
  },
  "sex": {
    "x": 50,
    "y": 1000
  },
  "trem2_variants": {
    "x": 50,
    "y": 1070
  },
  "bbb_penetration": {
    "x": 50,
    "y": 1270
  },
  "pink1_parkin": {
    "x": 50,
    "y": 1340
  },
  "senescent_cells": {
    "x": 50,
    "y": 1410
  },
  "c1q_elevated": {
    "x": 300,
    "y": 50
  },
  "rest_nuclear": {
    "x": 300,
    "y": 120
  },
  "meningeal_lymphatics": {
    "x": 300,
    "y": 190
  },
  "cypa_elevated": {
    "x": 300,
    "y": 260
  },
  "rest_depleted": {
    "x": 300,
    "y": 330
  },
  "er_ca_stores": {
    "x": 300,
    "y": 400
  },
  "mam_hyperconnectivity": {
    "x": 300,
    "y": 470
  },
  "senescent_trem2_microglia": {
    "x": 300,
    "y": 540
  },
  "cbs_enzyme": {
    "x": 300,
    "y": 610
  },
  "apoe4_domain_interaction": {
    "x": 300,
    "y": 680
  },
  "tlr4_activation": {
    "x": 300,
    "y": 750
  },
  "estrogen_level": {
    "x": 300,
    "y": 820
  },
  "trem2_surface": {
    "x": 300,
    "y": 890
  },
  "x_linked_lysosomal_genes": {
    "x": 300,
    "y": 960
  },
  "apoe4_ancestry_effect": {
    "x": 300,
    "y": 1030
  },
  "target_engagement": {
    "x": 300,
    "y": 1100
  },
  "female_iron_storage_failure": {
    "x": 300,
    "y": 1170
  },
  "testosterone_level": {
    "x": 300,
    "y": 1240
  },
  "dam_transition_blocked": {
    "x": 300,
    "y": 1310
  },
  "mtdna_cytosolic": {
    "x": 300,
    "y": 1380
  },
  "nrf2_pathway": {
    "x": 550,
    "y": 50
  },
  "glymphatic_clearance": {
    "x": 550,
    "y": 120
  },
  "mmp9_elevated": {
    "x": 550,
    "y": 190
  },
  "er_mito_ca_flux": {
    "x": 550,
    "y": 260
  },
  "gamma_secretase_mam": {
    "x": 550,
    "y": 330
  },
  "cystathionine": {
    "x": 550,
    "y": 400
  },
  "apoe_lipidation_reduced": {
    "x": 550,
    "y": 470
  },
  "ifn_gamma": {
    "x": 550,
    "y": 540
  },
  "lysosomal_cholesterol_sequestration": {
    "x": 550,
    "y": 610
  },
  "dam_stage1": {
    "x": 550,
    "y": 680
  },
  "visceral_adipose_tissue": {
    "x": 550,
    "y": 750
  },
  "plaque_compaction": {
    "x": 550,
    "y": 820
  },
  "strem2": {
    "x": 550,
    "y": 890
  },
  "biomarker_change": {
    "x": 550,
    "y": 960
  },
  "isf_abeta_clearance": {
    "x": 800,
    "y": 50
  },
  "pericyte_injury": {
    "x": 800,
    "y": 120
  },
  "mito_ca_overload_mam": {
    "x": 800,
    "y": 190
  },
  "cse_enzyme": {
    "x": 800,
    "y": 260
  },
  "abeta_clearance": {
    "x": 800,
    "y": 330
  },
  "astrocyte_lipid_droplets": {
    "x": 800,
    "y": 470
  },
  "dam_stage2": {
    "x": 800,
    "y": 540
  },
  "bbb_breakdown": {
    "x": 1050,
    "y": 50
  },
  "h2s_production": {
    "x": 1050,
    "y": 120
  },
  "cysteine": {
    "x": 1050,
    "y": 190
  },
  "plaque_barrier_function": {
    "x": 1050,
    "y": 330
  },
  "sulfhydration": {
    "x": 1300,
    "y": 50
  },
  "glutathione_gsh": {
    "x": 1300,
    "y": 120
  },
  "gsk3beta_sulfhydrated": {
    "x": 1550,
    "y": 50
  },
  "gpx4_activity": {
    "x": 1550,
    "y": 120
  },
  "mortality": {
    "x": 1800,
    "y": 50
  },
  "gsk3b_active": {
    "x": 1800,
    "y": 120
  },
  "lipid_peroxidation": {
    "x": 1800,
    "y": 190
  },
  "csf_biomarkers": {
    "x": 1800,
    "y": 260
  },
  "cognitive_score": {
    "x": 1800,
    "y": 330
  },
  "neuronal_count": {
    "x": 1800,
    "y": 400
  },
  "brain_volume": {
    "x": 1800,
    "y": 470
  },
  "synapses": {
    "x": 1800,
    "y": 540
  },
  "lysosomal_dysfunction": {
    "x": 1800,
    "y": 610
  },
  "lysosomal_genes_down": {
    "x": 1800,
    "y": 680
  },
  "tfeb_phosphorylated": {
    "x": 1800,
    "y": 750
  },
  "mitophagy_rate_reduced": {
    "x": 1800,
    "y": 820
  },
  "irs1_serine_phosphorylated": {
    "x": 1800,
    "y": 890
  },
  "insulin_resistance": {
    "x": 1800,
    "y": 960
  },
  "mtorc1_hyperactive": {
    "x": 1800,
    "y": 1030
  },
  "ulk1_phosphorylated": {
    "x": 1800,
    "y": 1100
  },
  "ampk_phosphorylated": {
    "x": 1800,
    "y": 1170
  },
  "sirt1_activity": {
    "x": 1870,
    "y": 1135
  },
  "s6k1_active": {
    "x": 1800,
    "y": 1240
  },
  "lmp": {
    "x": 1800,
    "y": 1310
  },
  "mtdna_from_lysosome": {
    "x": 1800,
    "y": 1380
  },
  "mtdna_undegraded": {
    "x": 1800,
    "y": 1450
  },
  "cargo_accumulation": {
    "x": 1800,
    "y": 1520
  },
  "lipofuscin": {
    "x": 1800,
    "y": 1590
  },
  "cathepsin_b_cytosolic": {
    "x": 1800,
    "y": 1660
  },
  "damaged_mito_pool": {
    "x": 1800,
    "y": 1730
  },
  "mitophagosome": {
    "x": 1800,
    "y": 1800
  },
  "autolysosome": {
    "x": 1800,
    "y": 1870
  },
  "mptp_open": {
    "x": 1800,
    "y": 1940
  },
  "ca_overload": {
    "x": 1800,
    "y": 2010
  },
  "mito_ros": {
    "x": 1800,
    "y": 2080
  },
  "mtdna_oxidized": {
    "x": 1800,
    "y": 2150
  },
  "ox_mtdna_cytosolic": {
    "x": 1800,
    "y": 2220
  },
  "vdac_oligomer": {
    "x": 1800,
    "y": 2290
  },
  "tau_hyperphosphorylated": {
    "x": 1800,
    "y": 2360
  },
  "neuroinflammation": {
    "x": 1800,
    "y": 2430
  },
  "nlrp3_active": {
    "x": 1800,
    "y": 2500
  },
  "caspase1_active": {
    "x": 1800,
    "y": 2570
  },
  "il1b": {
    "x": 1800,
    "y": 2640
  },
  "isg_expression": {
    "x": 1800,
    "y": 2710
  },
  "il18": {
    "x": 1800,
    "y": 2780
  },
  "type_i_ifn": {
    "x": 1800,
    "y": 2850
  },
  "sting_active": {
    "x": 1800,
    "y": 2920
  },
  "cgas_active": {
    "x": 1800,
    "y": 2990
  },
  "pp2a_activity": {
    "x": 1800,
    "y": 3060
  },
  "a1_astrocytes": {
    "x": 1800,
    "y": 3130
  },
  "glycolytic_switch": {
    "x": 1800,
    "y": 3200
  },
  "ldam": {
    "x": 1800,
    "y": 3270
  },
  "phagocytosis_impaired": {
    "x": 1800,
    "y": 3340
  },
  "il1a": {
    "x": 1800,
    "y": 3410
  },
  "microglia_activated": {
    "x": 1800,
    "y": 3480
  },
  "nf_kb_active": {
    "x": 1800,
    "y": 3550
  },
  "hif1a_stabilized": {
    "x": 1800,
    "y": 3620
  },
  "srebp1_active": {
    "x": 1800,
    "y": 3690
  },
  "lipid_droplets": {
    "x": 1800,
    "y": 3760
  },
  "c1q": {
    "x": 1800,
    "y": 3830
  },
  "tnf": {
    "x": 1800,
    "y": 3900
  },
  "app_processing_amyloidogenic": {
    "x": 1800,
    "y": 3970
  },
  "abeta_production": {
    "x": 1800,
    "y": 4040
  },
  "ltp_inhibition": {
    "x": 1800,
    "y": 4110
  },
  "synaptic_abeta_binding": {
    "x": 1800,
    "y": 4180
  },
  "abeta_oligomers": {
    "x": 1800,
    "y": 4250
  },
  "abeta_monomers": {
    "x": 1800,
    "y": 4320
  },
  "app_betactf": {
    "x": 1800,
    "y": 4390
  },
  "bace1_upregulated": {
    "x": 1800,
    "y": 4460
  },
  "abeta_plaques": {
    "x": 1800,
    "y": 4530
  },
  "neuronal_dysfunction": {
    "x": 1800,
    "y": 4600
  },
  "tau_seeding": {
    "x": 1800,
    "y": 4670
  },
  "tau_exosomal_release": {
    "x": 1800,
    "y": 4740
  },
  "tau_misfolded": {
    "x": 1800,
    "y": 4810
  },
  "pp2a_inhibited": {
    "x": 1800,
    "y": 4880
  },
  "p38_mapk_active": {
    "x": 1800,
    "y": 4950
  },
  "tau_aggregated": {
    "x": 1800,
    "y": 5020
  },
  "tau_aggregated_phf": {
    "x": 1800,
    "y": 5090
  },
  "nft_formation": {
    "x": 1800,
    "y": 5160
  },
  "c3_opsonization": {
    "x": 1800,
    "y": 5230
  },
  "cr3_mediated_pruning": {
    "x": 1800,
    "y": 5300
  },
  "synapse_elimination": {
    "x": 1800,
    "y": 5370
  },
  "functional_iron_deficiency": {
    "x": 1800,
    "y": 5440
  },
  "ferroptosis": {
    "x": 1800,
    "y": 5510
  },
  "lysosomal_iron_trap": {
    "x": 1800,
    "y": 5580
  },
  "labile_iron": {
    "x": 1800,
    "y": 5650
  },
  "ferroportin_reduced": {
    "x": 1800,
    "y": 5720
  },
  "iron_accumulation": {
    "x": 1800,
    "y": 5790
  },
  "ferritin_trap": {
    "x": 1800,
    "y": 5860
  },
  "hepcidin_elevated": {
    "x": 1800,
    "y": 5930
  },
  "white_matter_pathology": {
    "x": 1800,
    "y": 6000
  },
  "myelin_breakdown": {
    "x": 1800,
    "y": 6070
  },
  "cholinergic_degeneration": {
    "x": 1800,
    "y": 6140
  },
  "ach_reduced": {
    "x": 1800,
    "y": 6210
  },
  "clinical_benefit": {
    "x": 1800,
    "y": 6280
  },
  // New BBB/OL lineage nodes (added 2026-01-15)
  "bbb_integrity": {
    "x": 300,
    "y": 1450
  },
  "pericyte_function": {
    "x": 300,
    "y": 1520
  },
  "opcs": {
    "x": 550,
    "y": 1030
  },
  "mature_oligodendrocytes": {
    "x": 550,
    "y": 1100
  },
  "opc_nos1_activity": {
    "x": 550,
    "y": 1170
  },
  "ol_cholesterol_synthesis": {
    "x": 550,
    "y": 1240
  },
  "opc_tgf_beta1": {
    "x": 550,
    "y": 1310
  },
  "opc_vascular_coupling": {
    "x": 550,
    "y": 1380
  },
  "remyelination_capacity": {
    "x": 550,
    "y": 1450
  },
  // BMP lysosomal (Module 2)
  "bmp_lysosomal": {
    "x": 800,
    "y": 400
  }
};
