// Auto-generated by scripts/layout-network.ts
// Run: npx tsx scripts/layout-network.ts

export const nodePositions: Record<string, { x: number; y: number }> = {
  "sleep_disruption": {
    "x": 50,
    "y": 50
  },
  "exercise": {
    "x": 50,
    "y": 120
  },
  "aging": {
    "x": 50,
    "y": 320
  },
  "FSH_elevated": {
    "x": 50,
    "y": 520
  },
  "familial_AD_mutations": {
    "x": 50,
    "y": 590
  },
  "APOE_genotype": {
    "x": 50,
    "y": 660
  },
  "homocysteine": {
    "x": 50,
    "y": 860
  },
  "AS01_adjuvant": {
    "x": 50,
    "y": 930
  },
  "sex": {
    "x": 50,
    "y": 1000
  },
  "TREM2_variants": {
    "x": 50,
    "y": 1070
  },
  "BBB_penetration": {
    "x": 50,
    "y": 1270
  },
  "PINK1_Parkin": {
    "x": 50,
    "y": 1340
  },
  "senescent_cells": {
    "x": 50,
    "y": 1410
  },
  "C1q_elevated": {
    "x": 300,
    "y": 50
  },
  "REST_nuclear": {
    "x": 300,
    "y": 120
  },
  "meningeal_lymphatics": {
    "x": 300,
    "y": 190
  },
  "CypA_elevated": {
    "x": 300,
    "y": 260
  },
  "REST_depleted": {
    "x": 300,
    "y": 330
  },
  "ER_Ca_stores": {
    "x": 300,
    "y": 400
  },
  "MAM_hyperconnectivity": {
    "x": 300,
    "y": 470
  },
  "senescent_TREM2_microglia": {
    "x": 300,
    "y": 540
  },
  "CBS_enzyme": {
    "x": 300,
    "y": 610
  },
  "APOE4_domain_interaction": {
    "x": 300,
    "y": 680
  },
  "TLR4_activation": {
    "x": 300,
    "y": 750
  },
  "estrogen_level": {
    "x": 300,
    "y": 820
  },
  "TREM2_surface": {
    "x": 300,
    "y": 890
  },
  "X_linked_lysosomal_genes": {
    "x": 300,
    "y": 960
  },
  "APOE4_ancestry_effect": {
    "x": 300,
    "y": 1030
  },
  "target_engagement": {
    "x": 300,
    "y": 1100
  },
  "female_iron_storage_failure": {
    "x": 300,
    "y": 1170
  },
  "testosterone_level": {
    "x": 300,
    "y": 1240
  },
  "DAM_transition_blocked": {
    "x": 300,
    "y": 1310
  },
  "mtDNA_cytosolic": {
    "x": 300,
    "y": 1380
  },
  "SASP": {
    "x": 300,
    "y": 1450
  },
  "Nrf2_pathway": {
    "x": 550,
    "y": 50
  },
  "glymphatic_clearance": {
    "x": 550,
    "y": 120
  },
  "MMP9_elevated": {
    "x": 550,
    "y": 190
  },
  "ER_mito_Ca_flux": {
    "x": 550,
    "y": 260
  },
  "gamma_secretase_MAM": {
    "x": 550,
    "y": 330
  },
  "cystathionine": {
    "x": 550,
    "y": 400
  },
  "APOE_lipidation_reduced": {
    "x": 550,
    "y": 470
  },
  "IFN_gamma": {
    "x": 550,
    "y": 540
  },
  "lysosomal_cholesterol_sequestration": {
    "x": 550,
    "y": 610
  },
  "DAM_stage1": {
    "x": 550,
    "y": 680
  },
  "visceral_adipose_tissue": {
    "x": 550,
    "y": 750
  },
  "plaque_compaction": {
    "x": 550,
    "y": 820
  },
  "sTREM2": {
    "x": 550,
    "y": 890
  },
  "biomarker_change": {
    "x": 550,
    "y": 960
  },
  "ISF_Abeta_clearance": {
    "x": 800,
    "y": 50
  },
  "pericyte_injury": {
    "x": 800,
    "y": 120
  },
  "mito_Ca_overload_MAM": {
    "x": 800,
    "y": 190
  },
  "CSE_enzyme": {
    "x": 800,
    "y": 260
  },
  "Abeta_clearance": {
    "x": 800,
    "y": 330
  },
  "amyloid_clearance_enhanced": {
    "x": 800,
    "y": 400
  },
  "astrocyte_lipid_droplets": {
    "x": 800,
    "y": 470
  },
  "DAM_stage2": {
    "x": 800,
    "y": 540
  },
  "BBB_breakdown": {
    "x": 1050,
    "y": 50
  },
  "H2S_production": {
    "x": 1050,
    "y": 120
  },
  "cysteine": {
    "x": 1050,
    "y": 190
  },
  "cognitive_function": {
    "x": 1050,
    "y": 260
  },
  "plaque_barrier_function": {
    "x": 1050,
    "y": 330
  },
  "sulfhydration": {
    "x": 1300,
    "y": 50
  },
  "glutathione_GSH": {
    "x": 1300,
    "y": 120
  },
  "GSK3beta_sulfhydrated": {
    "x": 1550,
    "y": 50
  },
  "GPX4_activity": {
    "x": 1550,
    "y": 120
  },
  "mortality": {
    "x": 1800,
    "y": 50
  },
  "GSK3B_active": {
    "x": 1800,
    "y": 120
  },
  "lipid_peroxidation": {
    "x": 1800,
    "y": 190
  },
  "CSF_biomarkers": {
    "x": 1800,
    "y": 260
  },
  "cognitive_score": {
    "x": 1800,
    "y": 330
  },
  "neuronal_count": {
    "x": 1800,
    "y": 400
  },
  "brain_volume": {
    "x": 1800,
    "y": 470
  },
  "synapses": {
    "x": 1800,
    "y": 540
  },
  "lysosomal_dysfunction": {
    "x": 1800,
    "y": 610
  },
  "lysosomal_genes_down": {
    "x": 1800,
    "y": 680
  },
  "TFEB_phosphorylated": {
    "x": 1800,
    "y": 750
  },
  "mitophagy_rate_reduced": {
    "x": 1800,
    "y": 820
  },
  "IRS1_serine_phosphorylated": {
    "x": 1800,
    "y": 890
  },
  "insulin_resistance": {
    "x": 1800,
    "y": 960
  },
  "mTORC1_hyperactive": {
    "x": 1800,
    "y": 1030
  },
  "ULK1_phosphorylated": {
    "x": 1800,
    "y": 1100
  },
  "AMPK_phosphorylated": {
    "x": 1800,
    "y": 1170
  },
  "S6K1_active": {
    "x": 1800,
    "y": 1240
  },
  "LMP": {
    "x": 1800,
    "y": 1310
  },
  "mtDNA_from_lysosome": {
    "x": 1800,
    "y": 1380
  },
  "mtDNA_undegraded": {
    "x": 1800,
    "y": 1450
  },
  "cargo_accumulation": {
    "x": 1800,
    "y": 1520
  },
  "lipofuscin": {
    "x": 1800,
    "y": 1590
  },
  "cathepsin_B_cytosolic": {
    "x": 1800,
    "y": 1660
  },
  "damaged_mito_pool": {
    "x": 1800,
    "y": 1730
  },
  "mitophagosome": {
    "x": 1800,
    "y": 1800
  },
  "autolysosome": {
    "x": 1800,
    "y": 1870
  },
  "mPTP_open": {
    "x": 1800,
    "y": 1940
  },
  "Ca_overload": {
    "x": 1800,
    "y": 2010
  },
  "mito_ROS": {
    "x": 1800,
    "y": 2080
  },
  "mtDNA_oxidized": {
    "x": 1800,
    "y": 2150
  },
  "ox_mtDNA_cytosolic": {
    "x": 1800,
    "y": 2220
  },
  "VDAC_oligomer": {
    "x": 1800,
    "y": 2290
  },
  "tau_hyperphosphorylated": {
    "x": 1800,
    "y": 2360
  },
  "neuroinflammation": {
    "x": 1800,
    "y": 2430
  },
  "NLRP3_active": {
    "x": 1800,
    "y": 2500
  },
  "caspase1_active": {
    "x": 1800,
    "y": 2570
  },
  "IL1B": {
    "x": 1800,
    "y": 2640
  },
  "ISG_expression": {
    "x": 1800,
    "y": 2710
  },
  "IL18": {
    "x": 1800,
    "y": 2780
  },
  "type_I_IFN": {
    "x": 1800,
    "y": 2850
  },
  "STING_active": {
    "x": 1800,
    "y": 2920
  },
  "cGAS_active": {
    "x": 1800,
    "y": 2990
  },
  "PP2A_activity": {
    "x": 1800,
    "y": 3060
  },
  "A1_astrocytes": {
    "x": 1800,
    "y": 3130
  },
  "glycolytic_switch": {
    "x": 1800,
    "y": 3200
  },
  "LDAM": {
    "x": 1800,
    "y": 3270
  },
  "phagocytosis_impaired": {
    "x": 1800,
    "y": 3340
  },
  "IL1A": {
    "x": 1800,
    "y": 3410
  },
  "microglia_activated": {
    "x": 1800,
    "y": 3480
  },
  "NF_kB_active": {
    "x": 1800,
    "y": 3550
  },
  "HIF1A_stabilized": {
    "x": 1800,
    "y": 3620
  },
  "SREBP1_active": {
    "x": 1800,
    "y": 3690
  },
  "lipid_droplets": {
    "x": 1800,
    "y": 3760
  },
  "C1q": {
    "x": 1800,
    "y": 3830
  },
  "TNF": {
    "x": 1800,
    "y": 3900
  },
  "APP_processing_amyloidogenic": {
    "x": 1800,
    "y": 3970
  },
  "Abeta_production": {
    "x": 1800,
    "y": 4040
  },
  "LTP_inhibition": {
    "x": 1800,
    "y": 4110
  },
  "synaptic_Abeta_binding": {
    "x": 1800,
    "y": 4180
  },
  "Abeta_oligomers": {
    "x": 1800,
    "y": 4250
  },
  "Abeta_monomers": {
    "x": 1800,
    "y": 4320
  },
  "APP_betaCTF": {
    "x": 1800,
    "y": 4390
  },
  "BACE1_upregulated": {
    "x": 1800,
    "y": 4460
  },
  "Abeta_plaques": {
    "x": 1800,
    "y": 4530
  },
  "neuronal_dysfunction": {
    "x": 1800,
    "y": 4600
  },
  "tau_seeding": {
    "x": 1800,
    "y": 4670
  },
  "tau_exosomal_release": {
    "x": 1800,
    "y": 4740
  },
  "tau_misfolded": {
    "x": 1800,
    "y": 4810
  },
  "PP2A_inhibited": {
    "x": 1800,
    "y": 4880
  },
  "p38_MAPK_active": {
    "x": 1800,
    "y": 4950
  },
  "tau_aggregated": {
    "x": 1800,
    "y": 5020
  },
  "tau_aggregated_PHF": {
    "x": 1800,
    "y": 5090
  },
  "NFT_formation": {
    "x": 1800,
    "y": 5160
  },
  "C3_opsonization": {
    "x": 1800,
    "y": 5230
  },
  "CR3_mediated_pruning": {
    "x": 1800,
    "y": 5300
  },
  "synapse_elimination": {
    "x": 1800,
    "y": 5370
  },
  "functional_iron_deficiency": {
    "x": 1800,
    "y": 5440
  },
  "ferroptosis": {
    "x": 1800,
    "y": 5510
  },
  "lysosomal_iron_trap": {
    "x": 1800,
    "y": 5580
  },
  "labile_iron": {
    "x": 1800,
    "y": 5650
  },
  "ferroportin_reduced": {
    "x": 1800,
    "y": 5720
  },
  "iron_accumulation": {
    "x": 1800,
    "y": 5790
  },
  "ferritin_trap": {
    "x": 1800,
    "y": 5860
  },
  "hepcidin_elevated": {
    "x": 1800,
    "y": 5930
  },
  "white_matter_pathology": {
    "x": 1800,
    "y": 6000
  },
  "myelin_breakdown": {
    "x": 1800,
    "y": 6070
  },
  "cholinergic_degeneration": {
    "x": 1800,
    "y": 6140
  },
  "ACh_reduced": {
    "x": 1800,
    "y": 6210
  },
  "clinical_benefit": {
    "x": 1800,
    "y": 6280
  }
};
